name: app_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  signature: ^6.0.0
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.1
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  intl: ^0.20.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_final.png
    - assets/icon/app_icon.jpeg
